Repository Billing-Wise/server-api, pull requests merged in 2024-07, with the labels that each got.

#1 [cd] aws ecs 배포 자동화
  .github/workflows/cd.yml
  .gitignore
  build.gradle
Labels: cd

#2 [release] 0.0.1-SNAPSHOT
  .github/workflows/cd.yml
  .gitignore
  build.gradle
Labels: release

#3 [cd] ecs 태스크 정의
  task-definition.json
Labels: cd

#4 [release] 0.0.1-SNAPSHOT
  task-definition.json
Labels: cd

#5 [fix] 배포 시 gradle 권한 부여
  .github/workflows/cd.yml
Labels: fix

#6 [release] 0.0.1-SNAPSHOT
  .github/workflows/cd.yml
Labels: release

#7 [fix] 컨테이너 시간대 변경
  build.gradle
Labels: cd

#8 [release] 0.0.1-SNAPSHOT
  build.gradle
Labels: release

#9 [cd] 태스크 정의 로그 그룹 수정
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  task-definition.json
Labels: cd

#10 [release] 0.0.2-SNAPSHOT
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  task-definition.json
Labels: release

#11 [cd] cd 스크립트 버전 수정
  .github/workflows/cd.yml
Labels: cd

#12 [release] 0.0.2-SNAPSHOT
  .github/workflows/cd.yml
Labels: release

#13 [env] cors 허용
  src/main/java/site/billingwise/api/serverapi/global/config/WebConfig.java
Labels: env

#14 [release] 0.0.2-SNAPSHOT
  src/main/java/site/billingwise/api/serverapi/global/config/WebConfig.java
Labels: release

#15 [fix] cors 도메인 수정
  build.gradle
  src/main/java/site/billingwise/api/serverapi/global/config/WebConfig.java
Labels: env

#16 [env] 버전 수정
  build.gradle
Labels: env

#17 [release] 0.0.3-SNAPSHOT
  build.gradle
Labels: release

#18 [fix] cors 에러 수정
  src/main/java/site/billingwise/api/serverapi/global/config/WebConfig.java
Labels: fix

#19 [fix] cors 에러 수정
  src/main/java/site/billingwise/api/serverapi/global/config/WebConfig.java
  src/main/resources/application.yml
Labels: fix

#20 [K5P-38] [fix] cors 에러 수정
  src/main/resources/application.yml
Labels: fix

#21 [K5P-38] [fix] cors 에러 수정
  src/main/java/site/billingwise/api/serverapi/global/config/WebConfig.java
  src/main/resources/application.yml
Labels: fix

#22 [cd] cd 스크립트 브랜치 수정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cd.yml
Labels: cd

#23 [ci] 테스트 및 명세서 자동화
  .github/workflows/ci.yml
  build.gradle
  config/checkstyle/naver-checkstyle-rules.xml
  config/checkstyle/naver-checkstyle-suppressions.xml
Labels: ci

#24 [ci] rest docs 생성 스크립트 작성
  .github/workflows/api-docs.yml
  build.gradle
  src/docs/asciidoc/index.adoc
Labels: ci

#25 [release] 0.0.3-SNAPSHOT
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/api-docs.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  build.gradle
  config/checkstyle/naver-checkstyle-rules.xml
  config/checkstyle/naver-checkstyle-suppressions.xml
  src/docs/asciidoc/index.adoc
Labels: release

#26 [feat] 엔티티 구현
  build.gradle
  config/checkstyle/naver-checkstyle-rules.xml
  docker-compose.yml
  src/main/java/site/billingwise/api/serverapi/domain/common/BaseEntity.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/Contract.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/ContractStatus.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/PaymentType.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/Invoice.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/InvoiceType.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/PaymentStatus.java
  src/main/java/site/billingwise/api/serverapi/domain/item/Item.java
  src/main/java/site/billingwise/api/serverapi/domain/member/ConsentAccount.java
  src/main/java/site/billingwise/api/serverapi/domain/member/Member.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/Payment.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/PaymentAccount.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/PaymentCard.java
  src/main/java/site/billingwise/api/serverapi/domain/user/Client.java
  src/main/java/site/billingwise/api/serverapi/domain/user/User.java
  src/main/java/site/billingwise/api/serverapi/global/config/WebConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V2407080441__schema.sql
Labels: feat

#27 [feat] 응답 객체 및 전역 예외 처리 구현
  build.gradle
  src/main/java/site/billingwise/api/serverapi/global/config/SecurityConfig.java
  src/main/java/site/billingwise/api/serverapi/global/exception/GlobalException.java
  src/main/java/site/billingwise/api/serverapi/global/exception/GlobalExceptionHandler.java
  src/main/java/site/billingwise/api/serverapi/global/response/BaseResponse.java
  src/main/java/site/billingwise/api/serverapi/global/response/DataResponse.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
Labels: feat

#29 [feat] 사용자 등록 API
  .github/workflows/api-docs.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/billingwise/api/serverapi/ServerApiApplication.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/controller/AuthController.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/RegisterDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/AuthService.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/PaymentType.java
  src/main/java/site/billingwise/api/serverapi/domain/user/repository/ClientRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/user/repository/UserRepository.java
  src/main/java/site/billingwise/api/serverapi/global/config/JpaConfig.java
  src/main/resources/db/migration/V2407081242__fix_payment_type.sql
  src/test/java/ServerApiApplicationTests.java
  src/test/java/site/billingwise/api/serverapi/docs/restdocs/AbstractRestDocsTests.java
  src/test/java/site/billingwise/api/serverapi/domain/auth/controller/AuthControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/auth/service/AuthServiceTest.java
  src/test/resources/application.yml
Labels: feat

#31 [feat] 상품 이미지 수정 API
  src/docs/asciidoc/api/item.adoc
  src/main/java/site/billingwise/api/serverapi/domain/item/controller/ItemController.java
  src/main/java/site/billingwise/api/serverapi/domain/item/repository/ItemRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/item/service/ItemService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/item/controller/ItemControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/item/service/ItemServiceTest.java
Labels: feat

#33 [feat] 로그인 API
  .github/workflows/ci.yml
  build.gradle
  docker-compose.yml
  src/docs/asciidoc/api/auth.adoc
  src/main/java/site/billingwise/api/serverapi/domain/auth/CustomUserDetails.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/controller/AuthController.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/LoginDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/AuthService.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/CustomUserDetailService.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/Contract.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/ContractStatus.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/PaymentType.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/Invoice.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/InvoiceType.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/PaymentStatus.java
  src/main/java/site/billingwise/api/serverapi/domain/item/Item.java
  src/main/java/site/billingwise/api/serverapi/domain/member/ConsentAccount.java
  src/main/java/site/billingwise/api/serverapi/domain/member/Member.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/Payment.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/PaymentAccount.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/PaymentCard.java
  src/main/java/site/billingwise/api/serverapi/domain/user/Client.java
  src/main/java/site/billingwise/api/serverapi/domain/user/User.java
  src/main/java/site/billingwise/api/serverapi/domain/user/repository/UserRepository.java
  src/main/java/site/billingwise/api/serverapi/global/config/RedisConfig.java
  src/main/java/site/billingwise/api/serverapi/global/config/SecurityConfig.java
  src/main/java/site/billingwise/api/serverapi/global/config/WebConfig.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/JwtProvider.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/RefreshToken.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/RefreshTokenRedisRepository.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/resources/application-dev.yml
  src/test/java/site/billingwise/api/serverapi/domain/auth/controller/AuthControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/auth/service/AuthServiceTest.java
Labels: feat

#35 [feat] 로그아웃 & 토큰 재발급 API
  src/docs/asciidoc/api/auth.adoc
  src/main/java/site/billingwise/api/serverapi/domain/auth/CustomUserDetails.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/controller/AuthController.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/AuthService.java
  src/main/java/site/billingwise/api/serverapi/global/config/SecurityConfig.java
  src/main/java/site/billingwise/api/serverapi/global/config/WebConfig.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/JwtFilter.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/JwtProvider.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/RefreshToken.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/RefreshTokenRedisRepository.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/main/java/site/billingwise/api/serverapi/global/util/CookieUtil.java
  src/main/java/site/billingwise/api/serverapi/global/util/SecurityUtil.java
  src/test/java/site/billingwise/api/serverapi/docs/restdocs/AbstractRestDocsTests.java
  src/test/java/site/billingwise/api/serverapi/domain/auth/controller/AuthControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/auth/service/AuthServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/item/controller/ItemControllerTest.java
  src/test/java/site/billingwise/api/serverapi/global/WithMockCustomUser.java
  src/test/java/site/billingwise/api/serverapi/global/WithMockCustomUserSecurityContextFactory.java
Labels: feat

#34 [feat] 상품 상세 조회 API
  src/docs/asciidoc/api/item.adoc
  src/main/java/site/billingwise/api/serverapi/domain/item/Item.java
  src/main/java/site/billingwise/api/serverapi/domain/item/controller/ItemController.java
  src/main/java/site/billingwise/api/serverapi/domain/item/dto/request/CreateItemDto.java
  src/main/java/site/billingwise/api/serverapi/domain/item/dto/request/EditItemDto.java
  src/main/java/site/billingwise/api/serverapi/domain/item/dto/response/GetItemDto.java
  src/main/java/site/billingwise/api/serverapi/domain/item/repository/ItemRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/item/service/ItemService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/item/controller/ItemControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/item/service/ItemServiceTest.java
Labels: feat

#36 [feat] 이메일 중복 검사 API
  src/docs/asciidoc/api/auth.adoc
  src/main/java/site/billingwise/api/serverapi/domain/auth/controller/AuthController.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/request/EmailDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/request/LoginDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/request/RegisterDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/AuthService.java
  src/main/java/site/billingwise/api/serverapi/global/config/SecurityConfig.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/auth/controller/AuthControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/auth/service/AuthServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/item/controller/ItemControllerTest.java
Labels: feat

#39 [feat] 메일 인증 코드 전송 API
  src/docs/asciidoc/api/auth.adoc
  src/main/java/site/billingwise/api/serverapi/domain/auth/controller/AuthController.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/AuthService.java
  src/main/java/site/billingwise/api/serverapi/global/mail/MailCode.java
  src/main/java/site/billingwise/api/serverapi/global/mail/MailCodeRedisRepository.java
  src/main/java/site/billingwise/api/serverapi/global/mail/MailService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/main/resources/application.yml
  src/test/java/site/billingwise/api/serverapi/domain/auth/controller/AuthControllerTest.java
Labels: feat

#41 [feat] 이메일 인증 API
  src/docs/asciidoc/api/auth.adoc
  src/main/java/site/billingwise/api/serverapi/domain/auth/controller/AuthController.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/request/EmailCodeDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/AuthService.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/CustomUserDetailService.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/JwtProvider.java
  src/main/java/site/billingwise/api/serverapi/global/mail/EmailCode.java
  src/main/java/site/billingwise/api/serverapi/global/mail/EmailCodeRedisRepository.java
  src/main/java/site/billingwise/api/serverapi/global/mail/EmailService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/auth/controller/AuthControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/auth/service/AuthServiceTest.java
Labels: feat

#42 [feat] enum 컨버터 구현
  src/main/java/site/billingwise/api/serverapi/domain/common/EnumField.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/Contract.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/ContractStatus.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/PaymentType.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/Invoice.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/InvoiceType.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/PaymentStatus.java
  src/main/java/site/billingwise/api/serverapi/global/converter/AbstractConverter.java
  src/main/java/site/billingwise/api/serverapi/global/converter/ContractStatusConverter.java
  src/main/java/site/billingwise/api/serverapi/global/converter/InvoiceTypeConverter.java
  src/main/java/site/billingwise/api/serverapi/global/converter/PaymentStatusConverter.java
  src/main/java/site/billingwise/api/serverapi/global/converter/PaymentTypeConverter.java
  src/main/java/site/billingwise/api/serverapi/global/util/EnumUtil.java
Labels: feat

#44 [feat] 이메일 찾기 & 비밀번호 찾기 API
  build.gradle
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/api/member.adoc
  src/main/java/site/billingwise/api/serverapi/domain/auth/controller/AuthController.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/request/EmailDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/request/FindEmailDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/request/FindPasswordDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/request/PhoneCodeDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/request/PhoneDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/dto/request/RegisterDto.java
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/AuthService.java
  src/main/java/site/billingwise/api/serverapi/domain/member/dto/request/CreateMemberDto.java
  src/main/java/site/billingwise/api/serverapi/domain/user/User.java
  src/main/java/site/billingwise/api/serverapi/domain/user/repository/UserRepository.java
  src/main/java/site/billingwise/api/serverapi/global/mail/EmailService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/main/java/site/billingwise/api/serverapi/global/sms/PhoneCode.java
  src/main/java/site/billingwise/api/serverapi/global/sms/PhoneCodeRedisRepository.java
  src/main/java/site/billingwise/api/serverapi/global/sms/SmsService.java
  src/main/resources/application.yml
  src/test/java/site/billingwise/api/serverapi/domain/auth/controller/AuthControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/auth/service/AuthServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/member/controller/MemberControllerTest.java
Labels: feat

#47 [feat] 간편동의 상품설정 API & 동의서 등록 API
  src/docs/asciidoc/api/consent.adoc
  src/docs/asciidoc/api/setting.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/billingwise/api/serverapi/domain/consent/ConsentAccount.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/controller/ConsentController.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/dto/request/RegisterConsentDto.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/repository/ConsentAccountRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/ConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/Contract.java
  src/main/java/site/billingwise/api/serverapi/domain/item/Item.java
  src/main/java/site/billingwise/api/serverapi/domain/item/dto/response/GetItemDto.java
  src/main/java/site/billingwise/api/serverapi/domain/item/repository/ItemRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/member/Member.java
  src/main/java/site/billingwise/api/serverapi/domain/member/repository/MemberRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/member/service/MemberService.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/Payment.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/PaymentMethod.java
  src/main/java/site/billingwise/api/serverapi/domain/setting/controller/SettingController.java
  src/main/java/site/billingwise/api/serverapi/domain/setting/dto/request/SetBasicItemsDto.java
  src/main/java/site/billingwise/api/serverapi/domain/setting/service/SettingService.java
  src/main/java/site/billingwise/api/serverapi/domain/user/Client.java
  src/main/java/site/billingwise/api/serverapi/domain/user/repository/UserRepository.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/main/java/site/billingwise/api/serverapi/global/util/SecurityUtil.java
  src/main/resources/application.yml
  src/test/java/site/billingwise/api/serverapi/domain/consent/controller/ConsentControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/service/ConsentServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/item/controller/ItemControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/member/service/MemberServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/setting/controller/SettingControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/setting/service/SettingServiceTest.java
Labels: feat

#48 [feat] 동의정보 API
  src/docs/asciidoc/api/consent.adoc
  src/main/java/site/billingwise/api/serverapi/domain/consent/ConsentAccount.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/controller/ConsentController.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/dto/response/GetConsentDto.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/ConsentService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/controller/ConsentControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/service/ConsentServiceTest.java
Labels: feat

#50 [feat] 비회원 간편동의 상품목록 조회 API & 회원 간편동의 계약정보 조회 API
  src/docs/asciidoc/api/easy-consent.adoc
  src/docs/asciidoc/api/item.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/billingwise/api/serverapi/domain/consent/controller/EasyConsentController.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/dto/response/GetBasicItemDto.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/dto/response/GetContractInfoDto.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/item/repository/ItemRepository.java
  src/main/java/site/billingwise/api/serverapi/global/config/SecurityConfig.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/controller/EasyConsentControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentServiceTest.java
Labels: feat

#52 [feat] 비회원 간편동의 API
  src/docs/asciidoc/api/easy-consent.adoc
  src/main/java/site/billingwise/api/serverapi/domain/consent/controller/EasyConsentController.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/dto/request/ConsentWithNonMemberDto.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/ConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/item/repository/ItemRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/member/repository/MemberRepository.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/controller/EasyConsentControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentServiceTest.java
Labels: feat

#53 [feat] 회원 간편동의 API
  src/docs/asciidoc/api/easy-consent.adoc
  src/main/java/site/billingwise/api/serverapi/domain/consent/controller/EasyConsentController.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/dto/response/GetContractInfoDto.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/repository/ContractRepository.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/controller/EasyConsentControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentServiceTest.java
Labels: feat

#54 [feat] 청구 API 기능 구현
  src/main/java/site/billingwise/api/serverapi/domain/contract/dto/response/PaymentTypeDto.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/Invoice.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/controller/InvoiceController.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/dto/request/CreateInvoiceDto.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/dto/request/EditInvoiceDto.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/dto/response/GetInvoiceDto.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/dto/response/GetInvoiceListDto.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/dto/response/InvoiceItemDto.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/dto/response/InvoiceMemberDto.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/dto/response/InvoiceTypeDto.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/dto/response/PaymentStatusDto.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/repository/InvoiceRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/repository/InvoiceSpecification.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceService.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/repository/PaymentRepository.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
Labels: feat

#56 [feat] pay api 서버 feignclient로 연결
  src/main/java/site/billingwise/api/serverapi/ServerApiApplication.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/dto/request/ConsentWithNonMemberDto.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/dto/request/RegisterConsentDto.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/controller/PaymentController.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/dto/request/PayerPayAccountDto.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/dto/request/PayerPayCardDto.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/service/PaymentService.java
  src/main/java/site/billingwise/api/serverapi/global/config/SecurityConfig.java
  src/main/java/site/billingwise/api/serverapi/global/feign/PayClient.java
  src/main/java/site/billingwise/api/serverapi/global/feign/PayClientResponse.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/main/resources/application.yml
Labels: feat

#57 [feat] 카드 납부자 결제 API
  src/docs/asciidoc/api/payer-payment.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/billingwise/api/serverapi/domain/payment/Payment.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/PaymentAccount.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/PaymentCard.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/dto/request/PayerPayCardDto.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/repository/PaymentCardRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/service/PaymentService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/payment/controller/PaymentControllerTest.java
Labels: feat

#58 [feat] 계좌 납부자 결제 API
  src/docs/asciidoc/api/payer-payment.adoc
  src/main/java/site/billingwise/api/serverapi/domain/common/BaseEntity.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/dto/request/PayerPayAccountDto.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/repository/PaymentAccountRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/service/PaymentService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/payment/controller/PaymentControllerTest.java
Labels: feat

#60 [feat] 납부자결제 청구정보 조회 API
  src/docs/asciidoc/api/payer-payment.adoc
  src/main/java/site/billingwise/api/serverapi/domain/payment/controller/PaymentController.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/dto/response/GetPayerPayInvoiceDto.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/service/PaymentService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/payment/controller/PaymentControllerTest.java
Labels: feat

#62 [feat] 현재 사용자 정보 조회 API
  src/docs/asciidoc/api/user.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/billingwise/api/serverapi/domain/user/User.java
  src/main/java/site/billingwise/api/serverapi/domain/user/controller/UserController.java
  src/main/java/site/billingwise/api/serverapi/domain/user/dto/response/GetCurrentUserDto.java
  src/main/java/site/billingwise/api/serverapi/domain/user/repository/ClientRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/user/repository/UserRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/user/service/UserService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/test/java/site/billingwise/api/serverapi/domain/user/controller/UserControllerTest.java
Labels: feat

#64 [releas, fix] 배포 시 prod 프로필 적용
  build.gradle
  src/main/resources/application-prod.yml
Labels: release, fix

#65 [fix, realease] task definition & cd.yml 수정
  .github/workflows/cd.yml
  build.gradle
  task-definition.json
Labels: release, fix

#66 [fix, release] 기본 상품 이미지 경로 수정
  src/main/resources/application.yml
Labels: release, fix

#68 [env, release] 통계 스키마
  src/main/java/site/billingwise/api/serverapi/domain/member/service/MemberService.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/service/PaymentService.java
  src/main/java/site/billingwise/api/serverapi/global/util/PoiUtil.java
  src/main/resources/db/migration/V2407221052__statistics_schema.sql
Labels: env, release

#71 [fix] 계약 엔티티 및 목록 조회 수정
  src/main/java/site/billingwise/api/serverapi/domain/contract/Contract.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/controller/ContractController.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/repository/ContractSpecification.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/service/ContractService.java
  src/test/java/site/billingwise/api/serverapi/domain/contract/controller/ContractControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/contract/service/ContractServiceTest.java
Labels: fix

#72 [release] 1.0.1
  build.gradle
  src/docs/asciidoc/api/item.adoc
  src/docs/asciidoc/api/member.adoc
  src/main/java/site/billingwise/api/serverapi/domain/contract/Contract.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/controller/ContractController.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/repository/ContractSpecification.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/service/ContractService.java
  src/main/java/site/billingwise/api/serverapi/domain/item/controller/ItemController.java
  src/main/java/site/billingwise/api/serverapi/domain/item/dto/request/CreateItemDto.java
  src/main/java/site/billingwise/api/serverapi/domain/item/dto/request/EditItemDto.java
  src/main/java/site/billingwise/api/serverapi/domain/item/service/ItemService.java
  src/main/java/site/billingwise/api/serverapi/domain/member/Member.java
  src/main/java/site/billingwise/api/serverapi/domain/member/controller/MemberController.java
  src/main/java/site/billingwise/api/serverapi/domain/member/repository/MemberRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/member/repository/MemberSpecification.java
  src/main/java/site/billingwise/api/serverapi/domain/member/service/MemberService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/util/PoiUtil.java
  src/main/resources/db/migration/V2407241005__delete_constraint.sql
  src/test/java/site/billingwise/api/serverapi/domain/contract/controller/ContractControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/contract/service/ContractServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/item/controller/ItemControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/item/service/ItemServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/member/controller/MemberControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/member/service/MemberServiceTest.java
Labels: release

#73 [fix] 회원 간편동의 시 대기 중인 계약 진행으로 변경
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/repository/ContractRepository.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceServiceTest.java
Labels: fix

#75 [env] 프로메테우스 의존성 추가
  build.gradle
  docker-compose.yml
  src/main/java/site/billingwise/api/serverapi/global/config/SecurityConfig.java
  src/main/java/site/billingwise/api/serverapi/global/config/WebConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: env

#77 [env] prod 프로필에 프론트 주소 정의
  src/main/resources/application-prod.yml
Labels: env

#78 [release] 1.0.2
  src/main/resources/application-prod.yml
Labels: release

#79 [env] task definition 수정
  task-definition.json
Labels: env

#80 [release] 1.0.2
  task-definition.json
Labels: release

#81 [fix] task definition 불필요한 설정 삭제
  task-definition.json
Labels: fix

#82 [fix] 납부자 결제 수정
  src/main/java/site/billingwise/api/serverapi/domain/payment/service/PaymentService.java
Labels: fix

#83 [fix] 상품 조회 시 기본 설정 여부 반환
  src/main/java/site/billingwise/api/serverapi/domain/item/dto/response/GetItemDto.java
Labels: fix

#85 [feat] 통계 엔티티 구현
  src/main/java/site/billingwise/api/serverapi/domain/invoice/PaymentStatus.java
  src/main/java/site/billingwise/api/serverapi/domain/member/Member.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/InvoiceStats.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/InvoiceStatsType.java
  src/main/java/site/billingwise/api/serverapi/domain/user/Client.java
  src/main/java/site/billingwise/api/serverapi/global/converter/InvoiceStatsTypeConverter.java
  src/main/resources/db/migration/V2407311326__fix_invoice_statistics.sql
Labels: feat

#88 [feat] API 요청 응답 로깅
  build.gradle
  src/main/java/site/billingwise/api/serverapi/global/log/HttpLogMessage.java
  src/main/java/site/billingwise/api/serverapi/global/log/ReqResLoggingFilter.java
  src/main/resources/application.yml
Labels: feat

#89 [env] Q클래스 gitignore 설정
  .gitignore
Labels: env

#90 [release] 1.0.3
  .gitignore
  build.gradle
  src/docs/asciidoc/api/consent.adoc
  src/docs/asciidoc/api/invoice.adoc
  src/docs/asciidoc/api/static.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/billingwise/api/serverapi/domain/consent/controller/ConsentController.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/ConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/controller/ContractController.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/dto/request/EditContractDto.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/repository/ContractRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/service/ContractService.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/PaymentStatus.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/controller/InvoiceController.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/repository/InvoiceSpecification.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceService.java
  src/main/java/site/billingwise/api/serverapi/domain/item/dto/response/GetItemDto.java
  src/main/java/site/billingwise/api/serverapi/domain/member/Member.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/service/PaymentService.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/InvoiceStats.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/InvoiceStatsType.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/controller/InvoiceStatsController.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/dto/InvoiceStatsDto.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/repository/InvoiceStatsRepository.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/repository/InvoiceStatsRepositoryCustom.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/repository/InvoiceStatsRepositoryCustomImpl.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/service/InvoiceStatsService.java
  src/main/java/site/billingwise/api/serverapi/domain/user/Client.java
  src/main/java/site/billingwise/api/serverapi/global/config/QueryDslConfig.java
  src/main/java/site/billingwise/api/serverapi/global/converter/InvoiceStatsTypeConverter.java
  src/main/java/site/billingwise/api/serverapi/global/log/HttpLogMessage.java
  src/main/java/site/billingwise/api/serverapi/global/log/ReqResLoggingFilter.java
  src/main/java/site/billingwise/api/serverapi/global/mail/EmailService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V2407311326__fix_invoice_statistics.sql
  src/test/java/site/billingwise/api/serverapi/domain/consent/controller/ConsentControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/consent/service/ConsentServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/contract/service/ContractServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/invoice/controller/InvoiceControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/item/controller/ItemControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/stats/controller/InvoiceStatsControllerTest.java
  task-definition.json
Labels: release

#91 [fix] 로그 구조 json으로 변경
  src/main/java/site/billingwise/api/serverapi/global/log/HttpLogMessage.java
  src/main/java/site/billingwise/api/serverapi/global/log/ReqResLoggingFilter.java
Labels: fix

#92 [release] 1.0.3
  src/main/java/site/billingwise/api/serverapi/global/log/HttpLogMessage.java
  src/main/java/site/billingwise/api/serverapi/global/log/ReqResLoggingFilter.java
Labels: release

#95 [feat] api 호출만 로깅 및 민감정보 마스킹
  src/main/java/site/billingwise/api/serverapi/global/log/ApiLogMessage.java
  src/main/java/site/billingwise/api/serverapi/global/log/ApiLoggingFilter.java
Labels: feat

#96 [release] 1.0.3
  build.gradle
  src/main/java/site/billingwise/api/serverapi/global/log/ApiLogMessage.java
  src/main/java/site/billingwise/api/serverapi/global/log/ApiLoggingFilter.java
  src/test/java/site/billingwise/api/serverapi/domain/stats/controller/InvoiceStatsControllerTest.java
Labels: release
