Repository Billing-Wise/server-api, pull requests merged in 2024-08, with the labels that each got.

#99 [feat] DB Replica 적용 및 DataSource 라우팅
  build.gradle
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/AuthService.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/ConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/service/PaymentService.java
  src/main/java/site/billingwise/api/serverapi/domain/user/CustomUserDetails.java
  src/main/java/site/billingwise/api/serverapi/domain/user/service/CustomUserDetailService.java
  src/main/java/site/billingwise/api/serverapi/domain/user/service/UserService.java
  src/main/java/site/billingwise/api/serverapi/global/config/DataSourceConfig.java
  src/main/java/site/billingwise/api/serverapi/global/datasource/RoutingDataSource.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/JwtProvider.java
  src/main/java/site/billingwise/api/serverapi/global/util/SecurityUtil.java
  src/main/resources/application-prod.yml
  src/test/java/site/billingwise/api/serverapi/domain/auth/service/AuthServiceTest.java
  src/test/java/site/billingwise/api/serverapi/global/WithMockCustomUserSecurityContextFactory.java
Labels: feat

#100 [release] 1.0.4
  build.gradle
  src/main/java/site/billingwise/api/serverapi/domain/auth/service/AuthService.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/ConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/payment/service/PaymentService.java
  src/main/java/site/billingwise/api/serverapi/domain/stats/repository/InvoiceStatsRepositoryCustomImpl.java
  src/main/java/site/billingwise/api/serverapi/domain/user/CustomUserDetails.java
  src/main/java/site/billingwise/api/serverapi/domain/user/service/CustomUserDetailService.java
  src/main/java/site/billingwise/api/serverapi/domain/user/service/UserService.java
  src/main/java/site/billingwise/api/serverapi/global/config/DataSourceConfig.java
  src/main/java/site/billingwise/api/serverapi/global/datasource/RoutingDataSource.java
  src/main/java/site/billingwise/api/serverapi/global/jwt/JwtProvider.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/util/SecurityUtil.java
  src/main/resources/application-prod.yml
  src/test/java/site/billingwise/api/serverapi/domain/auth/service/AuthServiceTest.java
  src/test/java/site/billingwise/api/serverapi/global/WithMockCustomUserSecurityContextFactory.java
Labels: release

#102 [release] 1.0.4
  src/main/java/site/billingwise/api/serverapi/domain/contract/service/ContractService.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceService.java
  src/main/java/site/billingwise/api/serverapi/domain/item/service/ItemService.java
  src/main/java/site/billingwise/api/serverapi/domain/member/service/MemberService.java
  src/main/java/site/billingwise/api/serverapi/global/sms/SmsService.java
  src/test/java/site/billingwise/api/serverapi/domain/contract/service/ContractServiceTest.java
Labels: release

#104 [relase] 1.05
  build.gradle
  src/main/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceService.java
Labels: release

#105 [fix] 로깅 시 Client IP 실제 IP로 추출
  src/main/java/site/billingwise/api/serverapi/global/log/ApiLogMessage.java
Labels: fix

#106 [release] 1.0.5
  src/main/java/site/billingwise/api/serverapi/global/log/ApiLogMessage.java
Labels: release

#107 [fix] 자동이체 -> 실시간 CMS 변경
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/ConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/PaymentType.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceService.java
  src/main/resources/db/migration/V2408021616__fix_payment_type_name.sql
  src/test/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/contract/controller/ContractControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/contract/service/ContractServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/invoice/controller/InvoiceControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceServiceTest.java
Labels: fix

#108 [release] 1.0.5
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/ConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/PaymentType.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceService.java
  src/main/resources/db/migration/V2408021616__fix_payment_type_name.sql
  src/test/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/contract/controller/ContractControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/contract/service/ContractServiceTest.java
  src/test/java/site/billingwise/api/serverapi/domain/invoice/controller/InvoiceControllerTest.java
  src/test/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceServiceTest.java
Labels: release

#110 [fix] 회원 중복 허용
  .github/workflows/cd.yml
  build.gradle
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/ConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/global/util/CookieUtil.java
  src/main/java/site/billingwise/api/serverapi/global/util/EnumUtil.java
  src/main/java/site/billingwise/api/serverapi/global/util/PoiUtil.java
  src/main/java/site/billingwise/api/serverapi/global/util/SecurityUtil.java
Labels: fix

#111 [release] 1.0.6
  .github/workflows/cd.yml
  build.gradle
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/ConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/consent/service/EasyConsentService.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/controller/ContractController.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/dto/response/GetContractDto.java
  src/main/java/site/billingwise/api/serverapi/domain/contract/service/ContractService.java
  src/main/java/site/billingwise/api/serverapi/domain/invoice/service/InvoiceService.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/FailureInfo.java
  src/main/java/site/billingwise/api/serverapi/global/response/info/SuccessInfo.java
  src/main/java/site/billingwise/api/serverapi/global/util/CookieUtil.java
  src/main/java/site/billingwise/api/serverapi/global/util/EnumUtil.java
  src/main/java/site/billingwise/api/serverapi/global/util/PoiUtil.java
  src/main/java/site/billingwise/api/serverapi/global/util/SecurityUtil.java
  src/main/resources/db/migration/V2408031852__fix_column_order.sql
  src/test/java/site/billingwise/api/serverapi/domain/contract/controller/ContractControllerTest.java
Labels: release
